arm-angstrom-linux-gnueabi-gcc -c gamerunner_control.c -I/usr/include -lX11 -lSDL

#ccache arm-angstrom-linux-gnueabi-gcc -march=armv4t -mtune=arm920t -isystem/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os `pkg-config --cflags x11 xtst 2> /dev/null || echo "-I/usr/include/X11 -I/usr/include -I/usr/X11R6/include -I/usr/local/include"` -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -O1 `pkg-config --libs x11 xtst 2> /dev/null || echo "-L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst"` gamerunner_control.o xdo.o -o xdotool -lSDL

#ccache arm-angstrom-linux-gnueabi-gcc -march=armv4t -mtune=arm920t -isystem/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os -I/usr/include/X11 -I/usr/include -I/usr/X11R6/include -I/usr/local/include -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -O1 -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst gamerunner_control_for_dmenu.o xdo.o -o gr_control_for_dmenu -lSDL

arm-angstrom-linux-gnueabi-gcc -march=armv4t -mtune=arm920t -isystem/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os -I/usr/include/X11 -I/usr/include -I/usr/X11R6/include -I/usr/local/include -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -O1 -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst gamerunner_control.o xdo.o -o gr_game_control -lSDL

# arm-angstrom-linux-gnueabi-gcc -march=armv4t -mtune=arm920t -isystem/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os -I/usr/include/X11 -I/usr/include -I/usr/X11R6/include -I/usr/local/include -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -L/usr/local/openmoko/arm/arm-angstrom-linux-gnueabi/lib -O1 -L/usr/X11R6/lib -L/usr/local/lib -lX11 gamerunner_control.o xdo.o -o gr_game_control -lSDL
